name: radiator_king_device
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
